[package]
name = "cel_core"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
either = "1.15.0"
log = { version = "0.4", features = ["release_max_level_info"] }
portable-pty = "0.8.1"
vte = "0.13.0"
bitflags = "2.5.0"
unicode-width = "0.2"
unicode-segmentation = "1.10.1"
